Added basic Android build image.
dubit/docker-images pull request #1
Opened 2016-09-14 08:03 UTC by FenrirWillow

Still needs testing on our CI, working locally and able to build react-native applications.

2016-09-19 13:18 UTC, FenrirWillow commented
This is now fully implemented for React Native apps on our CI. Unless someone has some objections, sending this to the master branch.

2016-09-20 08:36 UTC, pmead commented on android-build/README.md
> +# Android applications build
Make this readme more useful try adding some simple usage instructions.
e.g.
`docker run --rm=true dubit/android-build -v path/to/project:/usr/src/app SomeBuildCommand`

2016-09-20 08:48 UTC, pmead requested changes
ReadMe could be better

2016-09-22 08:42 UTC, pmead approved these changes

2016-09-26 08:35 UTC, merged